all_parameters_must_be_in_file = false
simulation_boxsize = 800
simulation_name = "LCDM_plank13"
simulation_use_cola = true
simulation_use_scaledependent_cola = false
simulation_enforce_LPT_trajectories = false
simulation_cola_LPT_order = 2
cosmology_model = "LCDM"
cosmology_Omegab = 0.0483
cosmology_OmegaCDM = 0.2588
cosmology_OmegaMNu = 0
cosmology_OmegaK = 0.0
cosmology_Neffective = 3.046
cosmology_TCMB_kelvin = 2.7255
cosmology_h = 0.6777
particle_Npart_1D = 512
particle_allocation_factor = 1.2
timestep_nsteps = {10, 10}
timestep_method = "Tassev"
timestep_cola_nLPT = -2.5
timestep_scalefactor_spacing = "linear"
ic_initial_redshift = 10
ic_random_seed = 1111
ic_random_generator = "GSL"
ic_nmesh = particle_Npart_1D
ic_type_of_input = "powerspectrum"
ic_type_of_input_fileformat = "CAMB"
ic_input_filename = "/Your/file/of/power_spectrum.txt"
ic_input_redshift = 0.0
ic_sigma8 = 0.8288
ic_sigma8_redshift = 0.0
ic_random_field_type = "gaussian"
ic_LPT_order = 2
ic_use_gravity_model_GR = true
force_nmesh = particle_Npart_1D * 3
lightcone = false
output_folder = "/Your/dir/to/output/"
output_redshifts = {1.0, 0.0}
output_particles = true
output_fileformat = "GADGET"
fof = false
pofk = false
-- pofk_nmesh = particle_Npart_1D
-- pofk_interlacing = false
-- pofk_subtract_shotnoise = true
-- pofk_density_assignment_method = "CIC"
-- pofk_multipole = false
bispectrum = false
